name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1  # Use PHP 8.1.2 if available in the setup options

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts

      - name: Set Up Environment
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 u593348281@156.67.222.51 "cd /home/u593348281/domains/teachnurture.com/public_html/olintu && git pull origin main && composer install && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache"
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
